services:
  mongo:
    image: mongo:8
    container_name: mongo_product_service
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pwd
      MONGO_INITDB_DATABASE: products
    volumes:
      - mongo_data_shopping_ms:/data/db
    networks:
      - shopping-microservices-network

  postgres:
    image: postgres:18
    container_name: postgres_shopping_ms
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pwd
      POSTGRES_MULTIPLE_DATABASES: orders,inventory,auth
    volumes:
      - ./docker-init/db-init.sh:/docker-entrypoint-initdb.d/db-init.sh
      - postgres_data_shopping_ms:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - shopping-microservices-network


  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: auth
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: pwd
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8181:8080"
    depends_on:
      - postgres
    networks:
      - shopping-microservices-network

volumes:
  mongo_data_shopping_ms:
  postgres_data_shopping_ms:

networks:
  shopping-microservices-network:
    driver: bridge