services:
  mongo:
    image: mongo:8
    container_name: mongo_product_service
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pwd
      MONGO_INITDB_DATABASE: products
    volumes:
      - mongo_data_product_service:/data/db
    networks:
      - shopping-microservices-network

volumes:
  mongo_data_product_service:

networks:
  shopping-microservices-network:
    external: true