services:
  postgres:
    image: postgres:18
    container_name: postgres_order_service
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: orders
    volumes:
      - postgres_data_order_service:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - shopping-microservices-network

volumes:
  postgres_data_order_service:


networks:
  shopping-microservices-network:
    external: true
