server:
  port: 4020

spring:
  application:
    name: order-service

  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: admin
    password: pwd
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

clients:
  inventory:
    base-url: http://127.0.0.1:4030/api/inventory

springdoc:
  swagger-ui:
    path: /swagger/swagger-ui.html
    try-it-out-enabled: false
    supportedSubmitMethods:
    enabled: true
  api-docs:
    path: /swagger/api-docs
    enabled: true

